#!/usr/bin/env node
// Generic stdio JSON-RPC MCP server for the capsule container.
//
// This script is interpreted by the node already present in the base image, so
// it runs identically on linux/amd64 and linux/arm64 regardless of host OS or
// libc — unlike a compiled binary, which would have to match the container's
// target triple. It carries NO protocol knowledge of its own: the canned
// per-method results (initialize, tools/list) are generated by capsule from its
// Rust schema (see src/mcp_server.rs) and passed as argv[2].
//
// tools/call is a near-noop: the real verdict is read by capsule from Claude's
// output stream (the tool_use block), not from this server's reply. We still
// validate `status` against the schema's enum so a malformed call gets ok:false,
// matching the Rust server's behavior.

const fs = require("fs");

const manifestPath = process.argv[2];
const canned = JSON.parse(fs.readFileSync(manifestPath, "utf8"));

function statusEnum() {
  const tools = (canned["tools/list"] && canned["tools/list"].tools) || [];
  const tool = tools[0] || {};
  const props = (tool.inputSchema && tool.inputSchema.properties) || {};
  return (props.status && props.status.enum) || [];
}

function toolsCallResult(params) {
  const name = params && params.name;
  const tools = (canned["tools/list"] && canned["tools/list"].tools) || [];
  const known = tools.some((t) => t.name === name);
  const args = (params && params.arguments) || {};
  let payload;
  if (!known) {
    payload = { ok: false, error: "unknown tool" };
  } else if (!args.status || !statusEnum().includes(args.status)) {
    payload = { ok: false, error: "missing or invalid 'status' field" };
  } else {
    payload = { ok: true, verdict: { status: args.status, notes: args.notes ?? null } };
  }
  return { content: [{ type: "text", text: JSON.stringify(payload) }] };
}

function handle(msg) {
  // Notifications carry no id and expect no response.
  if (msg.method === undefined || msg.id === undefined) return null;

  let result;
  if (Object.prototype.hasOwnProperty.call(canned, msg.method)) {
    result = canned[msg.method];
  } else if (msg.method === "tools/call") {
    result = toolsCallResult(msg.params);
  } else {
    return {
      jsonrpc: "2.0",
      id: msg.id,
      error: { code: -32601, message: "Method not found" },
    };
  }
  return { jsonrpc: "2.0", id: msg.id, result };
}

const rl = require("readline").createInterface({ input: process.stdin });
rl.on("line", (line) => {
  if (!line.trim()) return;
  let msg;
  try {
    msg = JSON.parse(line);
  } catch {
    return;
  }
  const response = handle(msg);
  if (response !== null) {
    process.stdout.write(JSON.stringify(response) + "\n");
  }
});
